---
name: nginx-deployment

releases:
- name: nginx-deployment
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nginx-deployment
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
    # static_ips: [ 10.244.0.34 ]
  jobs:
  - name: nginx
    release: nginx-deployment
    properties:
      nginx_conf: |
        user nobody vcap; # group vcap can read most directories
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          ssi on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
            server_name localhost;
            listen *:80;
            access_log /var/vcap/sys/log/nginx/example.com-access.log;
            error_log /var/vcap/sys/log/nginx/example.com-error.log;
            root /var/vcap/data/nginx/document_root;
            index index.shtml;

            location / {
                auth_basic "Restricted Area. Please Login";
                auth_basic_user_file /var/vcap/jobs/nginx/conf/htpasswd;
            }
          }
        }
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/data/nginx/document_root
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $NGINX_DIR
          cd $NGINX_DIR
          cat > index.shtml <<EOF
            <html><head><title>My new BOSH Release on Virtualbox </title>
            </head><body>
            <h2>Welcome to my BOSH's nginx Release</h2>
            <h2>
            My hostname/IP: <b><!--# echo var="HTTP_HOST" --></b><br />
            Your IP: <b><!--# echo var="REMOTE_ADDR" --></b>
            </h2>
            </body></html>
        EOF
        fi
      # user_file: |
      # admin:$apr1$7slUwyza$MhQ1tv3QTjNu2Y/DoM6ln0
update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
